name: sc2-msspe
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::multiqc=1.8
  - bioconda::fastqc=0.11.8
  - bioconda::minimap2=2.17
  - bioconda::samtools=1.9
  - bioconda::trim-galore=0.6.5
  - bioconda::ivar=1.0.1
